# Generated by Django 5.0.6 on 2024-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_subject_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pdf_file',
            field=models.FileField(upload_to='units/'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
