# Generated by Django 5.0.6 on 2024-11-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
