# Generated by Django 5.0.6 on 2024-11-23 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_todotask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='created_at',
        ),
        migrations.AddField(
            model_name='todotask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
