# Generated by Django 5.0.6 on 2024-11-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_remove_todotask_completed_remove_todotask_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoTask',
        ),
    ]
